apiVersion: v1
kind: Service
metadata:
  name: immich-takeout-streamer
  namespace: immich
spec:
  selector:
    app: immich-takeout-streamer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
